BEGIN
DBMS_OUTPUT.PUT_LINE('HELLO WORLD!');
DBMS_OUTPUT.PUT_LINE('HELLO WORLD!');
END;

BEGIN
DBMS_OUTPUT.PUT_LINE('HELLO WORLD!');
DBMS_OUTPUT.PUT('HOW ARE YOU?');
DBMS_OUTPUT.PUT(', I AM FINE');
DBMS_OUTPUT.PUT_LINE(' ');
END;

DECLARE
	X NUMBER := 10;
    F FLOAT := 25.56;
    CH VARCHAR(25) := 'SHREE';
BEGIN
    DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
    DBMS_OUTPUT.PUT_LINE('THE VALUE OF F = '||F);
    DBMS_OUTPUT.PUT_LINE('THE VALUE OF CH = '||CH);
END;

DECLARE --FIRST
X NUMBER := 10;
BEGIN
    DECLARE --SECOND
    Y NUMBER := 20;
    BEGIN
        DECLARE --THIRD
        Z NUMBER := 30;
        BEGIN
            DBMS_OUTPUT.PUT_LINE('THIRD BLOCK := ');
            DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
            DBMS_OUTPUT.PUT_LINE('THE VALUE OF Y = '||Y);
            DBMS_OUTPUT.PUT_LINE('THE VALUE OF Z = '||Z);
        END; --THIRD
        DBMS_OUTPUT.PUT_LINE('SECOND BLOCK := ');
        DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
        DBMS_OUTPUT.PUT_LINE('THE VALUE OF Y = '||Y);
    END; --SECOND
    DBMS_OUTPUT.PUT_LINE('FIRST BLOCK := ');
    DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
END; --FIRST

DECLARE
	AGE NUMBER:=16;
BEGIN
IF AGE>18 THEN
	DBMS_OUTPUT.PUT_LINE('YOU ARE ELIGIBLE FOR VOTING');
ELSE
	DBMS_OUTPUT.PUT_LINE('YOU ARE NOT ELIGIBLE FOR VOTING');
END IF;
END;

DECLARE
	X NUMBER := 16;
BEGIN
IF MOD(X,2) = 0 THEN
	DBMS_OUTPUT.PUT_LINE(X||' IS AN EVEN NUMBER');
ELSE
	DBMS_OUTPUT.PUT_LINE(X||' IS AN ODD NUMBER');
END IF;
END;